export const AssetIds = {
  tiles: {
    fire: 'tile.fire',
    ice: 'tile.ice',
    lightning: 'tile.lightning',
    earth: 'tile.earth',
    empty: 'tile.empty',
  },
  powerUps: {
    rocketH: 'power.rocketH',
    rocketV: 'power.rocketV',
    tnt: 'power.tnt',
    lightball: 'power.lightball',
    lightballStream: 'power.lightballStream',
    orb: 'power.orb',
  },
  backdrops: {
    forest: 'backdrop.forest',
    crypt: 'backdrop.crypt',
    crystalCave: 'backdrop.crystalCave',
    castle: 'backdrop.castle',
    bg2: 'backdrop.bg2',
    bg3: 'backdrop.bg3',
    bg4: 'backdrop.bg4',
    bg5: 'backdrop.bg5',
    bg6: 'backdrop.bg6',
    bg7: 'backdrop.bg7',
  },
  rigs: {
    mage: 'rig.mage',
    kobold: 'rig.kobold',
    tallKobold: 'rig.tallKobold',
    boss: 'rig.boss',
  },
  ui: {
    hudBanner: 'ui.hudBanner',
    boardBackground: 'ui.boardBackground',
    levelTitlePanel: 'ui.levelTitlePanel',
    heartFill: 'ui.heartFill',
    heartEmpty: 'ui.heartEmpty',
    trialFillBarBg: 'ui.trialFillBarBg',
    trialFillBarFill: 'ui.trialFillBarFill',
    trialFillBarKoboldIcon: 'ui.trialFillBarKoboldIcon',
    primaryButton: 'ui.primaryButton',
    primaryButtonPressed: 'ui.primaryButtonPressed',
    tutorialFinger: 'ui.tutorialFinger',
    activateEarth: 'ui.activateEarth',
    activateFire: 'ui.activateFire',
    activateIce: 'ui.activateIce',
    activateLightning: 'ui.activateLightning',
    levelCleared: 'ui.levelCleared',
    floorCleared: 'ui.floorCleared',
    lifeLost: 'ui.lifeLost',
    gameOver: 'ui.gameOver',
  },
  materials: {
    mageTexture: 'material.mageTexture',
    koboldTexture: 'material.koboldTexture',
    bossTexture: 'material.bossTexture',
  },
  spritesheets: {
    tntExplosion: 'spritesheet.tntExplosion',
    rocketCloud: 'spritesheet.rocketCloud',
    fireBurn: 'spritesheet.fireBurn',
    earthImpact: 'spritesheet.earthImpact',
  },
  sounds: {
    tileMatch: 'sound.tileMatch',
    mergeMatch: 'sound.mergeMatch',
    matchCoin: 'sound.matchCoin',
    boardMove: 'sound.boardMove',
    boardMoveBack: 'sound.boardMoveBack',
    levelUp: 'sound.levelUp',
    enemyWalkLoop: 'sound.enemyWalkLoop',
    comboPitchStep: 'sound.comboPitchStep',
    fireWhoosh: 'sound.spell.fire.whoosh',
    iceWhoosh: 'sound.spell.ice.whoosh',
    lightningWhoosh: 'sound.spell.lightning.whoosh',
    earthWhoosh: 'sound.spell.earth.whoosh',
    fireImpact: 'sound.spell.fire.impact',
    iceImpact: 'sound.spell.ice.impact',
    lightningImpact: 'sound.spell.lightning.impact',
    earthImpact: 'sound.spell.earth.impact',
    monsterDamage: 'sound.monsterDamage',
    monsterDefeat: 'sound.monsterDefeat',
    playerDamage: 'sound.playerDamage',
    playerDefeat: 'sound.playerDefeat',
    powerupCreate: 'sound.powerupCreate',
    powerupBombActivate: 'sound.powerup.bombActivate',
    powerupRocketActivate: 'sound.powerup.rocketActivate',
    runEnd: 'sound.runEnd',
    uiClick: 'sound.uiClick',
    musicBackground: 'sound.musicBackground',
    levelStart: 'sound.levelStart',
  },
} as const;
