export const AssetIds = {
  tiles: {
    fire: 'tile.fire',
    ice: 'tile.ice',
    lightning: 'tile.lightning',
    earth: 'tile.earth',
    land: 'tile.land',
    path: 'tile.path',
  },
  powerUps: {
    rocketH: 'power.rocketH',
    rocketV: 'power.rocketV',
    tnt: 'power.tnt',
    lightball: 'power.lightball',
  },
  backdrops: {
    forest: 'backdrop.forest',
    crypt: 'backdrop.crypt',
    crystalCave: 'backdrop.crystalCave',
  },
  rigs: {
    mage: 'rig.mage',
    prince: 'rig.prince',
    kobold: 'rig.kobold',
    tallKobold: 'rig.tallKobold',
  },
  props: {
    princeCage: 'prop.princeCage',
    goalFlag: 'prop.goalFlag',
    abductorGlove: 'prop.abductorGlove',
    abductorHook: 'prop.abductorHook',
    abductorHand: 'prop.abductorHand',
    abductorRope: 'prop.abductorRope',
  },
  sounds: {
    tileMatch: 'sound.tileMatch',
    comboPitchStep: 'sound.comboPitchStep',
    fireWhoosh: 'sound.spell.fire.whoosh',
    iceWhoosh: 'sound.spell.ice.whoosh',
    lightningWhoosh: 'sound.spell.lightning.whoosh',
    earthWhoosh: 'sound.spell.earth.whoosh',
    fireImpact: 'sound.spell.fire.impact',
    iceImpact: 'sound.spell.ice.impact',
    lightningImpact: 'sound.spell.lightning.impact',
    earthImpact: 'sound.spell.earth.impact',
    pathConvert: 'sound.pathConvert',
    mageWalk: 'sound.mageWalk',
    monsterDamage: 'sound.monsterDamage',
    monsterDefeat: 'sound.monsterDefeat',
    powerupCreate: 'sound.powerupCreate',
    victorySting: 'sound.victorySting',
    cageYankWhoosh: 'sound.cageYankWhoosh',
    runEnd: 'sound.runEnd',
  },
} as const;
